const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CFT_BROWSER_PATH,headless:true});
 const out=path.resolve(process.env.CFT_OUTPUT_DIR || 'output');const tests=[];
 const context=await browser.newContext({viewport:{width:1440,height:1100}});
 const page=await context.newPage();const errors=[];const requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await page.goto('http://127.0.0.1:8765/');await page.waitForSelector('tbody tr');
 assert.equal(await page.locator('tbody tr').count(),20);tests.push('desktop renders 20 records');
 assert.equal(await page.locator('[data-stat=total]').innerText(),'20');
 await page.screenshot({path:path.join(out,'tracker-desktop.png'),fullPage:true});
 await page.screenshot({path:path.join(out,'tracker-desktop-viewport.png')});
 await page.locator('[name=municipality]').fill('Point Pleasant Beach');
 assert.equal(await page.locator('tbody tr').count(),0);assert.equal(await page.locator('[data-empty]').isVisible(),true);
 await page.locator('[name=municipality]').fill('Point Pleasant');assert.equal(await page.locator('tbody tr').count(),1);assert.equal(await page.locator('tbody tr').getAttribute('data-code'),'1525');tests.push('Point Pleasant Borough and Beach distinct');
 await page.locator('[type=reset]').click();await page.waitForFunction(()=>document.querySelectorAll('tbody tr').length===20);
 await page.locator('[name=county]').selectOption('Ocean');await page.locator('[name=status]').selectOption('verified_partial');assert.equal(await page.locator('tbody tr').count(),1);assert.match(await page.locator('tbody').innerText(),/Berkeley Township/);tests.push('combined county/status filters');
 await page.locator('summary').first().click();assert.equal(await page.locator('details').first().evaluate(e=>e.open),true);assert.match(await page.locator('tbody').innerText(),/Police Department or Finance Department/);tests.push('official refund instructions expand');
 await page.locator('[type=reset]').click();await page.waitForFunction(()=>document.querySelectorAll('tbody tr').length===20);
 await page.locator('[data-sort=refund_amount]').click();assert.equal(await page.locator('tbody tr').first().getAttribute('data-code'),'1506');
 await page.locator('[data-sort=refund_amount]').click();assert.match(await page.locator('tbody tr').first().innerText(),/Wall Township/);tests.push('numeric ascending/descending sort');
 await page.route('**/api/nj_carry_fee_relief.json',r=>r.abort());await page.reload();await page.waitForSelector('[data-feed-message]:not([hidden])');assert.match(await page.locator('[data-feed-message]').innerText(),/saved snapshot/);assert.equal(await page.locator('tbody tr').count(),20);tests.push('outage shows dated cached snapshot');
 const cold=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:2});const fail=await cold.newPage();await fail.route('**/api/nj_carry_fee_relief.json',r=>r.fulfill({status:503,body:'unavailable'}));await fail.goto('http://127.0.0.1:8765/');await fail.waitForSelector('[data-feed-message]:not([hidden])');assert.equal(await fail.locator('[data-stat=total]').innerText(),'—');assert.equal(await fail.locator('tbody tr').count(),0);tests.push('cold outage has no fabricated zero totals');await fail.screenshot({path:path.join(out,'tracker-unavailable-mobile.png'),fullPage:true});await cold.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:2});const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://127.0.0.1:8765/');await phone.waitForSelector('tbody tr');
 assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);tests.push('phone layout has no horizontal overflow');
 await phone.screenshot({path:path.join(out,'tracker-mobile.png'),fullPage:true});await phone.screenshot({path:path.join(out,'tracker-mobile-viewport.png')});
 await phone.locator('[name=municipality]').fill('Berkeley');await phone.locator('summary').first().click();assert.equal(await phone.locator('details').first().evaluate(e=>e.open),true);await phone.locator('tbody tr').first().scrollIntoViewIfNeeded();await phone.screenshot({path:path.join(out,'tracker-mobile-berkeley.png')});tests.push('phone cards and expanded instructions');
 await phone.goto('http://127.0.0.1:8765/alert/');await phone.waitForSelector('#actions a');assert.equal(await phone.locator('#actions a').count(),1);assert.equal(await phone.locator('#actions a').innerText(),'View Source');assert.equal(await phone.locator('#actions a').getAttribute('href'),'/nj-carry-permit-fee-refunds/');assert.match(await phone.locator('#body').innerText(),/Community credit: Teacher in NJ \(@teacher_in_nj\) and Jay Costa \(@jaycostausa\)\./);await phone.screenshot({path:path.join(out,'alert-mobile-preview.png'),fullPage:true});tests.push('Build 18 draft renders exact credit and one View Source link');
 assert.deepEqual(errors,[]);assert.equal(requests.some(u=>/firebase|fcm|googleapis/.test(u)),false);tests.push('no JS errors or Firebase/FCM requests');
 console.log(JSON.stringify({passed:tests.length,tests},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
